#!/bin/bash

set -e

printf "\n* Container prerm...\n"
printf "\n* Cleanup...\n"

if podman ps | awk '{print $2}' | grep -E '\blocalhost/ui(:|\b)'; then
    podman stop ui
fi

if podman images | awk '{print $1}' | grep -q ^localhost/ui$; then
    buildah rmi --force ui
fi

# Be sure there is not rubbish around.
if podman ps --all | awk '{print $2}' | grep -E '\blocalhost/ui(:|\b)'; then
    cIds=$( podman ps --all | awk '$2 ~ /^localhost\/ui/ { print $1 }' )
    for id in $cIds; do
        podman rm -f $id
    done
fi

exit 0

